digitalservicebund/erica

erica/request_processing/requests_controller.py
tests/request_processing/test_requests_controller.py

We sometimes have the problem that we want to test more than once per day the flow of request, activate and cancel unlock_code on production. We only have one test_idnr that we can use for that and are limited to performing this only once per day.
Therefore, this adds one more test IdNr to be used in production
- Use an array instead of a string
- Adapt tests
- Do you see any problem with this?

Add additional test idnr for production environment

---

Pipfile
Pipfile.lock
tests/request_processing/test_grundsteuer_request_controller.py
tests/samples/grundsteuer_sample_input.json
tests/samples/grundsteuer_sample_xml.xml

Improve json-to-xml conversion testing as a prerequisite for further development of the Grundsteuer API.
- Use json string as input instead of a Python dict to reflect the request payload more closely.
- Use the xmldiff library to compare expected and actual xml data for improved reliability and more useful output on failure.
- Fix typo in a certain Ms. Granger's name :)

Improve controller test

---

erica/application/EricaAuftrag/EricaAuftrag.py
erica/application/JobService/job.py
erica/application/JobService/job_service.py
erica/domain/erica_request/erica_request.py
erica/infrastructure/sqlalchemy/erica_request_schema.py
tests/application/job_service/test_job.py
tests/application/job_service/test_job_service.py
tests/infrastructure/sqlalechemy/repositories/test_erica_request_repository.py

This adds a failed status to an entity in the database if a job failed. For now, this happens in the job. However, if we want to use retries, we probably need to move that to a special exception handler.
This also adds the `error_code` and `error_message` to all EricaRequest classes and sets them if a job fails.
- Remove retries from job creation
- Change status if an EricProcessNotSuccessfulError occurred in a job
- Do you see any part that needs to be adapted with the error_message & error_code part that is currently missing?
- Do you see any tests that I missed?

Add failure status to database entity for failed jobs

---

erica/application/EricaAuftrag/EricaAuftrag.py
erica/application/FreischaltCode/Jobs/jobs.py
erica/application/JobService/job.py
erica/application/JobService/job_service.py
erica/application/tax_number_validation/jobs.py
erica/domain/erica_request/erica_request.py
erica/domain/repositories/base_repository_interface.py
erica/domain/repositories/erica_request_repository_interface.py
erica/infrastructure/sqlalchemy/erica_request_schema.py
erica/infrastructure/sqlalchemy/repositories/base_repository.py
erica/infrastructure/sqlalchemy/repositories/erica_request_repository.py
tests/application/FreischaltCode/test_freischaltcode_jobs.py
tests/application/job_service/test_job.py
tests/application/job_service/test_job_service.py
tests/application/tax_number_validation/test_check_tax_number_jobs.py
tests/infrastructure/sqlalechemy/repositories/mock_repositories.py
tests/infrastructure/sqlalechemy/repositories/test_base_repository.py
tests/infrastructure/sqlalechemy/repositories/test_erica_request_repository.py

For the EricaRequest we had one column named `job_id`. This was used to reference the request & was then also added as the actual job_id of the job that used that request entity to be run. 
This already lead to some miscommunication and misunderstanding.  Therefore, this column is now renamed to `request_id`. This can be used to reference a request from outside of Erica. Furthermore, the job_id is no longer set explicitly as we do not need to reference the job from the request entity.
- Rename column
- Rename all methods and attributes that are related to the request_id
- No longer set the job_id of the job explicitly
- Set the request_id as the parameter for the job
- No tests failed so far. However, we did not reference the entity correctly in the job (we set the entity.id but then used …

Add correct request UUID column

---

erica/erica_legacy/config.py
erica/infrastructure/rq/queue.py
erica/infrastructure/rq/worker.py
tests/infrastructure/rq/test_queue.py

For the connection to the redis in our running system we need a password. We can have all the information about the connection to the queue in the url. Therefore, this connects to the url using a url, that can be set through an env variable.
- Change config
- Change connection for worker
- Change connection for queue generation
- something I missed?

Use url to connect with redis

---

erica/erica_legacy/request_processing/requests_controller.py
tests/erica_legacy/request_processing/test_requests_controller.py

- PDF is now decoded so it can also be saved under the JSONB column of the postgres for v2
- Decoding the pdf
- Tests of v2 updated
- Julian will run the integration tests for v2 locally

NO_TICKET | decode pdf | Update tests

---

erica/api/exception_handling.py
erica/api/v2/responses/model.py

- The contract tests for v1 are failing because with the error handling we introduced a custom handler for RequestValidationError, which was needed because otherwise those errors would be catch with the interval_server_error handler (where we are catching all errors)
- For v2 was it ok because it is the new API
- For v1 it was no ok because that API is still relying on the default handler from FastAPI
- Removed custom handler for RequestValidationError and added default FastAPI handler.
- Do we need the errorCode/errorMessage response format for v2 in case of a RequestValidationError? In that case we need to specify an specific custom handler only for v2.
- Actually we had already the default handler also for v2 but I had to introduce a custom one because otherwise the …

NO_TICKET | Removed global custom handler RequestValidationError

---

.github/workflows/cicd-pipeline.yml

- This will create a second image tag "latest", beside the regular github run number. We need that in our steuerlotse docker compose for the local setup.
- Why do we need a hard coded image tag for the contract testing?

Add latest image tag

---

erica/infrastructure/sqlalchemy/database.py
tests/conftest.py

- Database migration initially used is now removed.
- Run_migrations removed from database.py, including unnecessary code
- Fixture in conftest adapted so that it doesn't rely on the removed run_migrations anymore
- Anything missing?

STL-2073 | Removed initial db migration | Fixture adapted

---

Dockerfile
entrypoint.sh
erica/cron.d/delete_success_fail_and_update_not_finished
erica/cron.d/delete_success_fail_entities
erica/cron.d/set_not_processed_entities_to_failed
erica/infrastructure/sqlalchemy/cron/update_entities_utils.py
erica/infrastructure/sqlalchemy/repositories/erica_request_repository.py
tests/infrastructure/sqlalechemy/repositories/test_erica_request_repository.py

- Finally the cron jobs for the erica should run
- Separated cron jobs, before they were in the same file (what is not possible)
- Corrected cron job definitions
- Added permission magement in the dockerfile for the cron jobs pasted to /etc/cron.d (needed as explained [here](https://unix.stackexchange.com/a/478581))
- Method renamed so that they better match the use case.
- Added env file definition in the entrypoint (needed at least for the ERICA_ENV since it was removed from the cron job definition) and as it is used in the webapp
- I tested them locally and they worked! But should try them also on staging.

STL-2050 | Fix cron jobs

---

erica/application/FreischaltCode/FreischaltCodeService.py
erica/application/JobService/job.py
erica/erica_legacy/pyeric/eric_errors.py
tests/api/test_api.py
tests/application/FreischaltCode/test_freischaltcode_service.py
tests/application/job_service/test_job.py

While working on grundsteuer I realized that we do not add the correct errors for validation problems instead we set the error code (a number not a string) and then the error message is just the short descriptor of the error. This changes that. We probably should change the error messages in errors.py in the future
- Add validation problems to Global Prüffehler answers
- Fix a small problem where we still did use idnr instead of tax_id_number
- Does this make sense to you?

Add validation problems

---

erica/erica_legacy/elster_xml/grundsteuer/elster_data_representation.py
tests/erica_legacy/elster_xml/common/test_electronic_steuernummer.py

- When implementing the feature, I didn't have Steuernummern/Aktenzeichen of all Bundesländer which is why I couldn't test the method properly. So I added tests with data from the Steuernummerprüfung-PDF from Elster, that includes exaples for each Bundesland.
- Add tests for create_aktenzeichen
- Only use create_aktenzeichen, not steuernummer, as it turns out that Eric's function already handles the steuernummer cases correctly
- ?

Generate aktenzeichen for all bundeslaender

---

contract_tests/test_integration_queue.py
erica/application/EricRequestProcessing/grundsteuer_request_controller.py
erica/application/FreischaltCode/FreischaltCode.py
erica/application/FreischaltCode/FreischaltCodeService.py
erica/application/Shared/response_dto.py
erica/application/grundsteuer/GrundsteuerService.py
erica/application/tax_declaration/TaxDeclarationService.py
erica/erica_legacy/api/v1/endpoints/est.py
erica/erica_legacy/api/v1/endpoints/grundsteuer.py
erica/erica_legacy/api/v1/endpoints/unlock_code.py
erica/erica_legacy/elster_xml/xml_parsing/elster_specifics_xml_parsing.py
erica/erica_legacy/request_processing/requests_controller.py
tests/api/test_api.py
tests/application/FreischaltCode/test_freischaltcode_jobs.py
tests/application/FreischaltCode/test_freischaltcode_service.py
tests/application/grundsteuer/test_grundsteuer_jobs.py
tests/application/grundsteuer/test_grundsteuer_service.py
tests/application/tax_declaration/test_tax_declaration_jobs.py
tests/application/tax_declaration/test_tax_declaration_service.py
tests/erica_legacy/elster_xml/xml_parsing/test_elster_tax_offices_xml_parsing.py
tests/erica_legacy/request_processing/test_grundsteuer_request_controller.py
tests/erica_legacy/request_processing/test_requests_controller.py

- Transferticket is actually one word, so why not export it as one word from Erica?
- Adapt the outputted data to use `transferticket` instead of `transfer_ticket`
- Add a check for transferticket (+pdf) in the contract tests (which didn't fail with my changes which I had expected)
- Do you think I should adapt the other snake-case variables, too? (in this PR?)
- Do you think it's be better to change all occurrences of transfer_ticket to transferticket, also in the deeper code (aka "legacy" folder)?
- Do you see a problem with pushing this? Rente is still using the v1, correct? So this should not be a problem? @SannyNguyenHung 

Use transferticket as one word

---

contract_tests/test_integration_queue.py
erica/application/JobService/job.py
erica/application/Shared/response_dto.py
erica/application/grundsteuer/GrundsteuerService.py
erica/application/grundsteuer/grundsteuer_dto.py
erica/application/grundsteuer/grundsteuer_input_grundstueck.py
erica/application/tax_declaration/TaxDeclarationService.py
erica/application/tax_declaration/tax_declaration_dto.py
tests/application/job_service/test_job.py

- Before, the validation problems were stored in the `error_message` column of the result table. However, as this had a VARCHAR datatype they were stored like this: `"{"Error 1", "Error 2"}`
- Now, they instead get stored in the `result` column
- Store validation_problems as dict in result + return as object
- Adapt test for non-validation errors no not include validation_problems
- Do we have any end-to-end tests that I should adapt to be sure this actually works as intended? Because so far, I think e.g. the ResponseDto is never actually tested?

Move validation problems into result response

---

erica/cron.d/set_not_processed_entities_to_failed

To ensure that we file early enough the cron job should run more often. Before it could happen that it would take 7 minutes for a job to fail (not being processed (2 minutes waiting time), cron job will run after 5 minutes)
- Reduce waiting time
- Do we need to adapt the other cron job, too?
- Does that make sense?

Run cron jobs every minute

---

erica/application/FreischaltCode/FreischaltCode.py
erica/domain/FreischaltCode/FreischaltCode.py
erica/erica_legacy/pyeric/check_elster_request_id.py
erica/erica_legacy/pyeric/utils.py
erica/erica_legacy/request_processing/requests_controller.py
tests/erica_legacy/pyeric/test_check_elster_request_id.py
tests/erica_legacy/pyeric/test_utils_.py
tests/erica_legacy/request_processing/test_requests_controller.py
tests/erica_legacy/samples/sample_vast_list.xml
tests/erica_legacy/samples/sample_vast_list_empty.xml

We do not need the id number to send an FSC request to erica. However, we do need it to make decide whether the testidnumber should be set. This allows us to check whether the testidnumber needs to be set by looking for the corresponding id number of an elster request.
- Add some utils functions to check whether a test merker is required
- Change how is_testmerker_used works for fsc activation and revocation
- Do you see any problem with this approach?
- Do you see any tests that might be useful (e.g. on an integration level or as contract tests)?

Make id number optional

---

README.md

- Update the URL of the DigitalService
- see #134
- Replace https://digitalservice4germany.com with https://digitalservice.bund.de
- Are other projects affected as well?

Update DigitalService URL

---

Pipfile
Pipfile.lock
erica/infrastructure/sqlalchemy/cron/update_entities_utils.py
scripts/create_tax_office_lists.py
scripts/list_permits.py
scripts/request_abruf_code.py
setup.py
tests/conftest.py

This is a "SHOW" PR @frederike-ramin @JulianRoesner @VictorDelCampo 
Just a small detail of python packaging that can make our lives easier.
If you make a package installable (by adding a minimal `setup.py`), you can add it to your Pipfile, which will automatically add it to the load path.
More about setup.py and all things packaging here: https://python-packaging.readthedocs.io/en/latest/minimal.html

Make "import erica" work without hacking sys.path

---

erica/erica_legacy/elster_xml/grundsteuer/elster_data_representation.py
tests/erica_legacy/elster_xml/grundsteuer/test_elster_data_representation.py

- As for eigentuemer it is not required to have the street set - instead it is either required to set the street or the postfach - we cannot simply set the AbsStr for the Absender to the eigentuemer street
- The not-so-pretty-but-in-my-head-completely-fine-solution for this is to in that case just set the AbsStr to the postfach. Especially since we learned that those are historic fields that aren't actually used for anything anymore at Elster's side.
- Set AbsStr to postfach if street not set
- Except from it being non-intuitive, do you see any problems with this?
[Link to Confluence](https://digitalservicebund.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

Avoid absender error if strasse not set

---

erica/erica_legacy/pyeric/eric_errors.py

- When implementing the re-requesting of FSCs in Grundsteuer, I was thinking about this and noticed that we ar enot exposing the specific "AlreadyRequestedFSC" error to clients. I think there's no harm in that?
- Explicitly add AlreadyRevokedError to possible error codes
- Do you see a reason we shouldn't do this?
[Link to Confluence](https://digitalservicebund.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

Expose FSC already revoked error to clients

---

erica/application/JobService/job.py
tests/application/job_service/test_job.py

- Previously, we logged the Elster return code of all TransferErrors, resulting in some errors being logged twice
- Check the concrete EricTransferError class and only log for that
- Add tests for both cases
- Really more a SHOW @JulianRoesner 
[Link to Confluence](https://digitalservicebund.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

Only log elster error code of transfer errors

---

contract_tests/test_integration_queue.py
erica/application/FreischaltCode/FreischaltCode.py
erica/domain/FreischaltCode/FreischaltCode.py
erica/erica_legacy/elster_xml/elster_xml_generator.py
erica/erica_legacy/request_processing/eric_mapper.py
erica/erica_legacy/request_processing/erica_input/v1/erica_input.py
tests/erica_legacy/elster_xml/test_elster_xml_generator.py
tests/erica_legacy/request_processing/test_requests_controller.py

- Users of grundsteuer are confused because in their FSC letter it says "Veranlagungsjahr: 2021", although they ant to do the declaration for 2022 - to be able to configure that, I introduced an optional input parameter to differ from "2021" - this way it should work as normal until you provide a different tax_year.
- Add tax_year to all unlock_code_request input tapes
- Set tax_year in unlock_code_request XML
- I'm slightly confused if I introduced the default value in the right places. That I have to alter a type a full *three* times seems quite a lot to me and I' not sure I did this correctly.
- Do you see a good place to test that the input tax_year in the end results in the XML and that the default is set correctly? I'm not really satisfied with the test coverage on this one.
[Link …

Add optional tax_year to unlock_code_request

---

erica/worker/elster_xml/grundsteuer/elster_eigentuemer.py
erica/worker/request_processing/grundsteuer_request_controller.py
tests/worker/request_processing/test_grundsteuer_request_controller.py

The requirements are specified in https://steuerlotse.atlassian.net/browse/STL-2902?focusedCommentId=13022 
To recap:
SteuerID given: test/real submissions are determined using the 0 prefix (same as before).
SteuerID not given: environment-specific config determines whether to mark the submission as test (false on production, true on staging)

Make SteuerID in grundsteuer input optional.

---

erica/api/dto/grundsteuer_input_eigentuemer.py
erica/worker/pyeric/check_elster_request_id.py
scripts/list_permits.py
tests/api/dto/test_grundsteuer_input_eigentuemer.py

- Eigentümer with no SteuerID should now pass validation.
- One test case, `test_if_all_persons_have_test_tax_id_number_not_special_testmerker_then_raise_error`, did not seem to be doing what it claimed to and was equivalent to another test case further down, so I appropriated it to define a new test case.

Fix person validation on missing SteuerID.

---

Dockerfile

Upgrades [pcscd](https://packages.debian.org/bookworm/pcscd) and [pcsd-tools](https://packages.debian.org/bookworm/pcsc-tools) from bullseye (current debian stable) to bookworm (current debian testing). This is an attempt to fix the underlying issue that triggers the mysterious ERIC_CRYPT_E_SC_SLOT_EMPTY error.
- Adds the bookworm repository to apt sources.
- Installs pcscd and pcsc-tools from bookworm. Apart from these two and their dependencies (see links above for the list), sources of the rest of the packages should remain unchanged (i.e. bullseye).

Install pcsc from debian testing (bookworm).

---

erica/worker/pyeric/eric_errors.py
tests/worker/pyeric/test_eric_errors.py

- Error that we didn't yet catch: next to AlreadyRequested and AlreadyRevoked, we'll also need AlreadyActivated
- I'll catch this error in Grundsteuer before merging this, but a review would be great beforehand either way. :)
- Catch and throw special error
- Anything critical?
[Link to Confluence](https://digitalservicebund.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

Add special AlreadyActivated fsc error
